trigger:
    batch: true
    branches:
        include:
        - main
        - develop
        - Shaik_Ateeq_Intern
    paths:
        include: 
        - /Learning_Vue/VueProjects/recipe-app

pool:
  name: 'Azure Pipelines'


variables:
  isMain: $[eq(variables['Build.f'], 'refs/heads/main')] #not used
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')] #not used
  test: ""

stages:
- template: templates/stage_level_templates/test_build_stage_template.yml # stage template to test, build and push
  parameters:
    projectFolder: VueProjects/recipe-app #${{variables.projectFolder}}
    buildOutputFolder: VueProjects/recipe-app/dist #${{variables.buildOutputFolder}}
    sourceFolder: $(SOURCEFOLDER) #${{variables.sourceFolder}}
    vmImageName: $(VMIMAGE)
    

- template: templates/stage_level_templates/az_deployment_stage_template.yml # stage template for azure resource deployment to Develop
  parameters:
    vmImageName : $(VMIMAGE) #${{variables.vmImage}}
    azureSubscription : "venkatmpn"
    resourceGroup : "Venkat&Ateeq"
    bicepFilePath : "VueProjects/infrastructure/main.bicep"
    parameterFilePath : "VueProjects/infrastructure/main.parameters.dev.json"
    jobName : "resourcedeployment"
    jobDescription : "deployemnt of resources"
    scriptType : "bash"
    environment: 'dev'
    deploy: true

- template: templates/stage_level_templates/app_deployment_stage_template.yml #stage template for application deployment
  parameters:
    serviceConnection: "venkatmpn"
    subscriptionId: 'dev'
    environment: 'dev'
    appType: 'webApp'
    appName: 'ariqt-diet-solution'
